### ISSUE TITLE
Error parsing an empty section

### ISSUE THREAD

**Issue by opomuc** [tarantool/config#8]
```
default:
    log_directory: '/var/log/tarantool'
    work_dir: '.'
    log_level: 6

storage:
    # storage does not have custom options yet
```
```
local config = require('config')
local local_cfg = config.parse({ app_name = 'storage' })
```
```
.rocks\/share\/tarantool\/config.lua:89: bad argument #1 to 'pairs' (table expected, got string)
```
